CREATE TABLE vendor_service_mappings (
 vendor_service_mapping_id UUID PRIMARY KEY DEFAULT gen_random_uuid(), vendor_id UUID NOT NULL REFERENCES vendors(vendor_id) ON DELETE CASCADE, service_id UUID NOT NULL REFERENCES services(service_id) ON DELETE CASCADE,
 coverage_zone_id UUID REFERENCES coverage_zones(coverage_zone_id) ON DELETE RESTRICT, agreed_rate NUMERIC(15,2), status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
 created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP, created_by UUID REFERENCES users(user_id) ON DELETE SET NULL, updated_by UUID REFERENCES users(user_id) ON DELETE SET NULL, version BIGINT NOT NULL DEFAULT 0,
 CONSTRAINT uq_vendor_service_zone UNIQUE(vendor_id,service_id,coverage_zone_id), CONSTRAINT ck_vendor_rate CHECK(agreed_rate IS NULL OR agreed_rate>=0), CONSTRAINT ck_vendor_service_status CHECK(status IN('ACTIVE','INACTIVE','SUSPENDED')), CONSTRAINT ck_vendor_service_audit CHECK(updated_at>=created_at AND version>=0)
);
CREATE TABLE quotations (
 quotation_id UUID PRIMARY KEY DEFAULT gen_random_uuid(), service_request_id UUID NOT NULL REFERENCES service_requests(service_request_id) ON DELETE CASCADE, vendor_id UUID REFERENCES vendors(vendor_id) ON DELETE RESTRICT,
 pricing_estimate_id UUID REFERENCES pricing_estimates(pricing_estimate_id) ON DELETE RESTRICT, quotation_number VARCHAR(80) NOT NULL UNIQUE, amount NUMERIC(15,2) NOT NULL, currency_code CHAR(3) NOT NULL DEFAULT 'INR',
 status VARCHAR(20) NOT NULL DEFAULT 'DRAFT', valid_until TIMESTAMPTZ NOT NULL, terms TEXT,
 created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP, created_by UUID REFERENCES users(user_id) ON DELETE SET NULL, updated_by UUID REFERENCES users(user_id) ON DELETE SET NULL, version BIGINT NOT NULL DEFAULT 0,
 CONSTRAINT ck_quotation_amount CHECK(amount>=0), CONSTRAINT ck_quotation_currency CHECK(currency_code~'^[A-Z]{3}$'), CONSTRAINT ck_quotation_status CHECK(status IN('DRAFT','SUBMITTED','ACCEPTED','REJECTED','EXPIRED','CANCELLED')), CONSTRAINT ck_quotation_audit CHECK(updated_at>=created_at AND version>=0)
);
CREATE TABLE vendor_assignments (
 vendor_assignment_id UUID PRIMARY KEY DEFAULT gen_random_uuid(), service_request_id UUID NOT NULL REFERENCES service_requests(service_request_id) ON DELETE CASCADE, vendor_id UUID NOT NULL REFERENCES vendors(vendor_id) ON DELETE RESTRICT,
 quotation_id UUID REFERENCES quotations(quotation_id) ON DELETE RESTRICT, assigned_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP, accepted_at TIMESTAMPTZ, completed_at TIMESTAMPTZ, status VARCHAR(20) NOT NULL DEFAULT 'ASSIGNED', notes TEXT,
 created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP, created_by UUID REFERENCES users(user_id) ON DELETE SET NULL, updated_by UUID REFERENCES users(user_id) ON DELETE SET NULL, version BIGINT NOT NULL DEFAULT 0,
 CONSTRAINT uq_vendor_assignment UNIQUE(service_request_id,vendor_id), CONSTRAINT ck_vendor_assignment_status CHECK(status IN('ASSIGNED','ACCEPTED','DECLINED','IN_PROGRESS','COMPLETED','CANCELLED')), CONSTRAINT ck_vendor_assignment_times CHECK((accepted_at IS NULL OR accepted_at>=assigned_at) AND (completed_at IS NULL OR completed_at>=assigned_at)), CONSTRAINT ck_vendor_assignment_audit CHECK(updated_at>=created_at AND version>=0)
);
CREATE TABLE service_assignments (
 service_assignment_id UUID PRIMARY KEY DEFAULT gen_random_uuid(), service_request_id UUID NOT NULL REFERENCES service_requests(service_request_id) ON DELETE CASCADE,
 assignee_type VARCHAR(20) NOT NULL, agent_id UUID REFERENCES agents(agent_id) ON DELETE RESTRICT, vendor_id UUID REFERENCES vendors(vendor_id) ON DELETE RESTRICT,
 assigned_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP, unassigned_at TIMESTAMPTZ, status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE', assignment_reason TEXT,
 created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP, created_by UUID REFERENCES users(user_id) ON DELETE SET NULL, updated_by UUID REFERENCES users(user_id) ON DELETE SET NULL, version BIGINT NOT NULL DEFAULT 0,
 CONSTRAINT ck_service_assignee CHECK((assignee_type='AGENT' AND agent_id IS NOT NULL AND vendor_id IS NULL) OR (assignee_type='VENDOR' AND vendor_id IS NOT NULL AND agent_id IS NULL)), CONSTRAINT ck_service_assignment_status CHECK(status IN('ACTIVE','COMPLETED','CANCELLED')), CONSTRAINT ck_service_assignment_period CHECK(unassigned_at IS NULL OR unassigned_at>=assigned_at), CONSTRAINT ck_service_assignment_audit CHECK(updated_at>=created_at AND version>=0)
);
CREATE TABLE marketplace_listings (
 marketplace_listing_id UUID PRIMARY KEY DEFAULT gen_random_uuid(), property_id UUID NOT NULL REFERENCES properties(property_id) ON DELETE RESTRICT, seller_customer_id UUID NOT NULL REFERENCES customers(customer_id) ON DELETE RESTRICT,
 listing_type VARCHAR(20) NOT NULL, title VARCHAR(200) NOT NULL, description TEXT, asking_price NUMERIC(15,2), currency_code CHAR(3) NOT NULL DEFAULT 'INR', status VARCHAR(20) NOT NULL DEFAULT 'DRAFT', published_at TIMESTAMPTZ, expires_at TIMESTAMPTZ,
 created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP, created_by UUID REFERENCES users(user_id) ON DELETE SET NULL, updated_by UUID REFERENCES users(user_id) ON DELETE SET NULL, version BIGINT NOT NULL DEFAULT 0,
 CONSTRAINT ck_listing_type CHECK(listing_type IN('SALE','RENT','LEASE')), CONSTRAINT ck_listing_price CHECK(asking_price IS NULL OR asking_price>=0), CONSTRAINT ck_listing_currency CHECK(currency_code~'^[A-Z]{3}$'), CONSTRAINT ck_listing_status CHECK(status IN('DRAFT','PUBLISHED','PAUSED','CLOSED','EXPIRED')), CONSTRAINT ck_listing_period CHECK(expires_at IS NULL OR published_at IS NULL OR expires_at>published_at), CONSTRAINT ck_listing_audit CHECK(updated_at>=created_at AND version>=0)
);
CREATE TABLE marketplace_inquiries (
 marketplace_inquiry_id UUID PRIMARY KEY DEFAULT gen_random_uuid(), marketplace_listing_id UUID NOT NULL REFERENCES marketplace_listings(marketplace_listing_id) ON DELETE CASCADE,
 interested_customer_id UUID NOT NULL REFERENCES customers(customer_id) ON DELETE RESTRICT, message TEXT, status VARCHAR(20) NOT NULL DEFAULT 'NEW', responded_at TIMESTAMPTZ,
 created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP, created_by UUID REFERENCES users(user_id) ON DELETE SET NULL, updated_by UUID REFERENCES users(user_id) ON DELETE SET NULL, version BIGINT NOT NULL DEFAULT 0,
 CONSTRAINT ck_inquiry_status CHECK(status IN('NEW','CONTACTED','QUALIFIED','CLOSED','SPAM')), CONSTRAINT ck_inquiry_audit CHECK(updated_at>=created_at AND version>=0)
);
CREATE TABLE marketplace_contact_disclosures (
 contact_disclosure_id UUID PRIMARY KEY DEFAULT gen_random_uuid(), marketplace_inquiry_id UUID NOT NULL REFERENCES marketplace_inquiries(marketplace_inquiry_id) ON DELETE CASCADE,
 disclosed_by UUID NOT NULL REFERENCES users(user_id) ON DELETE RESTRICT, disclosure_scope VARCHAR(20) NOT NULL, consent_reference VARCHAR(255) NOT NULL, disclosed_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
 created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP, created_by UUID REFERENCES users(user_id) ON DELETE SET NULL, updated_by UUID REFERENCES users(user_id) ON DELETE SET NULL, version BIGINT NOT NULL DEFAULT 0,
 CONSTRAINT uq_inquiry_disclosure UNIQUE(marketplace_inquiry_id,disclosure_scope), CONSTRAINT ck_disclosure_scope CHECK(disclosure_scope IN('SELLER_TO_BUYER','BUYER_TO_SELLER','BOTH')), CONSTRAINT ck_disclosure_audit CHECK(updated_at>=created_at AND version>=0)
);
CREATE TABLE marketplace_commissions (
 marketplace_commission_id UUID PRIMARY KEY DEFAULT gen_random_uuid(), marketplace_listing_id UUID NOT NULL REFERENCES marketplace_listings(marketplace_listing_id) ON DELETE RESTRICT,
 marketplace_inquiry_id UUID REFERENCES marketplace_inquiries(marketplace_inquiry_id) ON DELETE RESTRICT, invoice_id UUID REFERENCES invoices(invoice_id) ON DELETE RESTRICT,
 basis_amount NUMERIC(15,2) NOT NULL, rate_percentage NUMERIC(7,4) NOT NULL, commission_amount NUMERIC(15,2) NOT NULL, currency_code CHAR(3) NOT NULL DEFAULT 'INR', status VARCHAR(20) NOT NULL DEFAULT 'CALCULATED',
 created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP, created_by UUID REFERENCES users(user_id) ON DELETE SET NULL, updated_by UUID REFERENCES users(user_id) ON DELETE SET NULL, version BIGINT NOT NULL DEFAULT 0,
 CONSTRAINT ck_commission_values CHECK(basis_amount>=0 AND rate_percentage>=0 AND rate_percentage<=100 AND commission_amount>=0), CONSTRAINT ck_commission_currency CHECK(currency_code~'^[A-Z]{3}$'), CONSTRAINT ck_commission_status CHECK(status IN('CALCULATED','INVOICED','PAID','WAIVED','CANCELLED')), CONSTRAINT ck_commission_audit CHECK(updated_at>=created_at AND version>=0)
);
CREATE INDEX idx_vendor_services_lookup ON vendor_service_mappings(service_id,coverage_zone_id,status); CREATE INDEX idx_quotations_request ON quotations(service_request_id,status); CREATE INDEX idx_vendor_assignments_request ON vendor_assignments(service_request_id,status);
CREATE INDEX idx_service_assignments_request ON service_assignments(service_request_id,status); CREATE INDEX idx_listings_status_type ON marketplace_listings(status,listing_type,published_at DESC); CREATE INDEX idx_inquiries_listing ON marketplace_inquiries(marketplace_listing_id,status,created_at DESC); CREATE INDEX idx_commissions_listing ON marketplace_commissions(marketplace_listing_id,status);
CREATE TRIGGER trg_vendor_services_audit BEFORE UPDATE ON vendor_service_mappings FOR EACH ROW EXECUTE FUNCTION set_audit_columns(); CREATE TRIGGER trg_quotations_audit BEFORE UPDATE ON quotations FOR EACH ROW EXECUTE FUNCTION set_audit_columns(); CREATE TRIGGER trg_vendor_assignments_audit BEFORE UPDATE ON vendor_assignments FOR EACH ROW EXECUTE FUNCTION set_audit_columns(); CREATE TRIGGER trg_service_assignments_audit BEFORE UPDATE ON service_assignments FOR EACH ROW EXECUTE FUNCTION set_audit_columns();
CREATE TRIGGER trg_listings_audit BEFORE UPDATE ON marketplace_listings FOR EACH ROW EXECUTE FUNCTION set_audit_columns(); CREATE TRIGGER trg_inquiries_audit BEFORE UPDATE ON marketplace_inquiries FOR EACH ROW EXECUTE FUNCTION set_audit_columns(); CREATE TRIGGER trg_disclosures_audit BEFORE UPDATE ON marketplace_contact_disclosures FOR EACH ROW EXECUTE FUNCTION set_audit_columns(); CREATE TRIGGER trg_commissions_audit BEFORE UPDATE ON marketplace_commissions FOR EACH ROW EXECUTE FUNCTION set_audit_columns();
COMMENT ON TABLE vendor_service_mappings IS 'Vendor service capabilities by coverage zone.'; COMMENT ON TABLE quotations IS 'Commercial quotations for service requests.'; COMMENT ON TABLE vendor_assignments IS 'Vendor allocation and acceptance workflow.'; COMMENT ON TABLE service_assignments IS 'Canonical agent or vendor assignment ledger.';
COMMENT ON TABLE marketplace_listings IS 'Customer property marketplace listings.'; COMMENT ON TABLE marketplace_inquiries IS 'Buyer or tenant interest in listings.'; COMMENT ON TABLE marketplace_contact_disclosures IS 'Consent-backed exchange of marketplace contact details.'; COMMENT ON TABLE marketplace_commissions IS 'Marketplace commission calculations and collection state.';
DO $$ DECLARE t text; c text; BEGIN FOREACH t IN ARRAY ARRAY['vendor_service_mappings','quotations','vendor_assignments','service_assignments','marketplace_listings','marketplace_inquiries','marketplace_contact_disclosures','marketplace_commissions'] LOOP FOREACH c IN ARRAY ARRAY['created_at','updated_at','created_by','updated_by','version'] LOOP EXECUTE format('COMMENT ON COLUMN %I.%I IS %L',t,c,'Standard audit metadata.'); END LOOP; END LOOP; END $$;
DO $$ DECLARE r record; BEGIN FOR r IN SELECT table_name,column_name FROM information_schema.columns WHERE table_schema=current_schema() AND table_name=ANY(ARRAY['vendor_service_mappings','quotations','vendor_assignments','service_assignments','marketplace_listings','marketplace_inquiries','marketplace_contact_disclosures','marketplace_commissions']) AND column_name NOT IN('created_at','updated_at','created_by','updated_by','version') LOOP EXECUTE format('COMMENT ON COLUMN %I.%I IS %L',r.table_name,r.column_name,replace(initcap(replace(r.column_name,'_',' ')),' Id',' identifier.')); END LOOP; END $$;
