CREATE TABLE notification_templates (
 notification_template_id UUID PRIMARY KEY DEFAULT gen_random_uuid(), template_code VARCHAR(80) NOT NULL, channel VARCHAR(20) NOT NULL, locale VARCHAR(10) NOT NULL DEFAULT 'en', subject_template TEXT, body_template TEXT NOT NULL, status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
 created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP, created_by UUID REFERENCES users(user_id) ON DELETE SET NULL, updated_by UUID REFERENCES users(user_id) ON DELETE SET NULL, version BIGINT NOT NULL DEFAULT 0,
 CONSTRAINT uq_notification_template UNIQUE(template_code,channel,locale), CONSTRAINT ck_template_channel CHECK(channel IN('EMAIL','SMS','PUSH','WHATSAPP','IN_APP')), CONSTRAINT ck_template_status CHECK(status IN('ACTIVE','INACTIVE')), CONSTRAINT ck_template_audit CHECK(updated_at>=created_at AND version>=0)
);
CREATE TABLE notifications (
 notification_id UUID PRIMARY KEY DEFAULT gen_random_uuid(), user_id UUID NOT NULL REFERENCES users(user_id) ON DELETE CASCADE, notification_template_id UUID REFERENCES notification_templates(notification_template_id) ON DELETE SET NULL,
 channel VARCHAR(20) NOT NULL, subject TEXT, body TEXT NOT NULL, status VARCHAR(20) NOT NULL DEFAULT 'PENDING', scheduled_at TIMESTAMPTZ, sent_at TIMESTAMPTZ, read_at TIMESTAMPTZ, provider_message_id VARCHAR(255), failure_reason TEXT,
 created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP, created_by UUID REFERENCES users(user_id) ON DELETE SET NULL, updated_by UUID REFERENCES users(user_id) ON DELETE SET NULL, version BIGINT NOT NULL DEFAULT 0,
 CONSTRAINT ck_notification_channel CHECK(channel IN('EMAIL','SMS','PUSH','WHATSAPP','IN_APP')), CONSTRAINT ck_notification_status CHECK(status IN('PENDING','QUEUED','SENT','DELIVERED','FAILED','READ','CANCELLED')), CONSTRAINT ck_notification_times CHECK((sent_at IS NULL OR sent_at>=created_at) AND (read_at IS NULL OR sent_at IS NOT NULL AND read_at>=sent_at)), CONSTRAINT ck_notification_audit CHECK(updated_at>=created_at AND version>=0)
);
CREATE TABLE complaints (
 complaint_id UUID PRIMARY KEY DEFAULT gen_random_uuid(), customer_id UUID NOT NULL REFERENCES customers(customer_id) ON DELETE RESTRICT, service_request_id UUID REFERENCES service_requests(service_request_id) ON DELETE RESTRICT,
 assigned_to UUID REFERENCES users(user_id) ON DELETE SET NULL, complaint_number VARCHAR(80) NOT NULL UNIQUE, category VARCHAR(50) NOT NULL, subject VARCHAR(200) NOT NULL, description TEXT NOT NULL,
 priority VARCHAR(20) NOT NULL DEFAULT 'MEDIUM', status VARCHAR(20) NOT NULL DEFAULT 'OPEN', resolution TEXT, resolved_at TIMESTAMPTZ,
 created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP, created_by UUID REFERENCES users(user_id) ON DELETE SET NULL, updated_by UUID REFERENCES users(user_id) ON DELETE SET NULL, version BIGINT NOT NULL DEFAULT 0,
 CONSTRAINT ck_complaint_priority CHECK(priority IN('LOW','MEDIUM','HIGH','CRITICAL')), CONSTRAINT ck_complaint_status CHECK(status IN('OPEN','IN_REVIEW','WAITING_CUSTOMER','RESOLVED','CLOSED','REJECTED')), CONSTRAINT ck_complaint_resolution CHECK((status IN('RESOLVED','CLOSED') AND resolved_at IS NOT NULL) OR status NOT IN('RESOLVED','CLOSED')), CONSTRAINT ck_complaint_audit CHECK(updated_at>=created_at AND version>=0)
);
CREATE TABLE complaint_comments (
 complaint_comment_id UUID PRIMARY KEY DEFAULT gen_random_uuid(), complaint_id UUID NOT NULL REFERENCES complaints(complaint_id) ON DELETE CASCADE, author_user_id UUID NOT NULL REFERENCES users(user_id) ON DELETE RESTRICT,
 comment_text TEXT NOT NULL, visibility VARCHAR(20) NOT NULL DEFAULT 'CUSTOMER', attachment_metadata JSONB NOT NULL DEFAULT '[]'::jsonb,
 created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP, created_by UUID REFERENCES users(user_id) ON DELETE SET NULL, updated_by UUID REFERENCES users(user_id) ON DELETE SET NULL, version BIGINT NOT NULL DEFAULT 0,
 CONSTRAINT ck_comment_text CHECK(length(btrim(comment_text))>0), CONSTRAINT ck_comment_visibility CHECK(visibility IN('INTERNAL','CUSTOMER')), CONSTRAINT ck_comment_attachments CHECK(jsonb_typeof(attachment_metadata)='array'), CONSTRAINT ck_comment_audit CHECK(updated_at>=created_at AND version>=0)
);
CREATE TABLE service_ratings (
 service_rating_id UUID PRIMARY KEY DEFAULT gen_random_uuid(), service_request_id UUID NOT NULL UNIQUE REFERENCES service_requests(service_request_id) ON DELETE CASCADE, customer_id UUID NOT NULL REFERENCES customers(customer_id) ON DELETE RESTRICT,
 rating SMALLINT NOT NULL, review_text TEXT, moderation_status VARCHAR(20) NOT NULL DEFAULT 'PENDING', moderated_by UUID REFERENCES users(user_id) ON DELETE SET NULL, moderated_at TIMESTAMPTZ,
 created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP, created_by UUID REFERENCES users(user_id) ON DELETE SET NULL, updated_by UUID REFERENCES users(user_id) ON DELETE SET NULL, version BIGINT NOT NULL DEFAULT 0,
 CONSTRAINT ck_service_rating CHECK(rating BETWEEN 1 AND 5), CONSTRAINT ck_rating_moderation CHECK(moderation_status IN('PENDING','APPROVED','REJECTED')), CONSTRAINT ck_rating_audit CHECK(updated_at>=created_at AND version>=0)
);
CREATE TABLE report_reviews (
 report_review_id UUID PRIMARY KEY DEFAULT gen_random_uuid(), report_id UUID NOT NULL REFERENCES reports(report_id) ON DELETE CASCADE, reviewer_user_id UUID NOT NULL REFERENCES users(user_id) ON DELETE RESTRICT,
 review_status VARCHAR(20) NOT NULL DEFAULT 'PENDING', comments TEXT, reviewed_at TIMESTAMPTZ,
 created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP, created_by UUID REFERENCES users(user_id) ON DELETE SET NULL, updated_by UUID REFERENCES users(user_id) ON DELETE SET NULL, version BIGINT NOT NULL DEFAULT 0,
 CONSTRAINT uq_report_reviewer UNIQUE(report_id,reviewer_user_id), CONSTRAINT ck_report_review_status CHECK(review_status IN('PENDING','APPROVED','CHANGES_REQUESTED','REJECTED')), CONSTRAINT ck_report_review_time CHECK((review_status='PENDING' AND reviewed_at IS NULL) OR review_status<>'PENDING'), CONSTRAINT ck_report_review_audit CHECK(updated_at>=created_at AND version>=0)
);
CREATE TABLE knowledge_base_articles (
 knowledge_base_article_id UUID PRIMARY KEY DEFAULT gen_random_uuid(), article_slug VARCHAR(160) NOT NULL UNIQUE, title VARCHAR(250) NOT NULL, summary TEXT, body TEXT NOT NULL, category VARCHAR(80) NOT NULL,
 status VARCHAR(20) NOT NULL DEFAULT 'DRAFT', published_at TIMESTAMPTZ, author_user_id UUID NOT NULL REFERENCES users(user_id) ON DELETE RESTRICT,
 created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP, created_by UUID REFERENCES users(user_id) ON DELETE SET NULL, updated_by UUID REFERENCES users(user_id) ON DELETE SET NULL, version BIGINT NOT NULL DEFAULT 0,
 CONSTRAINT ck_article_slug CHECK(article_slug~'^[a-z0-9]+(?:-[a-z0-9]+)*$'), CONSTRAINT ck_article_status CHECK(status IN('DRAFT','PUBLISHED','ARCHIVED')), CONSTRAINT ck_article_publish CHECK((status='PUBLISHED' AND published_at IS NOT NULL) OR status<>'PUBLISHED'), CONSTRAINT ck_article_audit CHECK(updated_at>=created_at AND version>=0)
);
CREATE TABLE customer_favorites (
 customer_favorite_id UUID PRIMARY KEY DEFAULT gen_random_uuid(), customer_id UUID NOT NULL REFERENCES customers(customer_id) ON DELETE CASCADE, favorite_type VARCHAR(20) NOT NULL,
 property_id UUID REFERENCES properties(property_id) ON DELETE CASCADE, marketplace_listing_id UUID REFERENCES marketplace_listings(marketplace_listing_id) ON DELETE CASCADE,
 created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP, created_by UUID REFERENCES users(user_id) ON DELETE SET NULL, updated_by UUID REFERENCES users(user_id) ON DELETE SET NULL, version BIGINT NOT NULL DEFAULT 0,
 CONSTRAINT ck_favorite_target CHECK((favorite_type='PROPERTY' AND property_id IS NOT NULL AND marketplace_listing_id IS NULL) OR (favorite_type='LISTING' AND marketplace_listing_id IS NOT NULL AND property_id IS NULL)), CONSTRAINT ck_favorite_audit CHECK(updated_at>=created_at AND version>=0)
);
CREATE UNIQUE INDEX uq_favorite_property ON customer_favorites(customer_id,property_id) WHERE property_id IS NOT NULL; CREATE UNIQUE INDEX uq_favorite_listing ON customer_favorites(customer_id,marketplace_listing_id) WHERE marketplace_listing_id IS NOT NULL;
CREATE TABLE customer_search_history (
 customer_search_history_id UUID PRIMARY KEY DEFAULT gen_random_uuid(), customer_id UUID NOT NULL REFERENCES customers(customer_id) ON DELETE CASCADE, search_type VARCHAR(30) NOT NULL,
 search_criteria JSONB NOT NULL, result_count INTEGER NOT NULL DEFAULT 0, searched_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
 created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP, created_by UUID REFERENCES users(user_id) ON DELETE SET NULL, updated_by UUID REFERENCES users(user_id) ON DELETE SET NULL, version BIGINT NOT NULL DEFAULT 0,
 CONSTRAINT ck_search_type CHECK(search_type IN('PROPERTY','MARKETPLACE','SERVICE')), CONSTRAINT ck_search_criteria CHECK(jsonb_typeof(search_criteria)='object'), CONSTRAINT ck_search_count CHECK(result_count>=0), CONSTRAINT ck_search_audit CHECK(updated_at>=created_at AND version>=0)
);
CREATE INDEX idx_notifications_delivery ON notifications(status,scheduled_at); CREATE INDEX idx_notifications_user ON notifications(user_id,created_at DESC); CREATE INDEX idx_complaints_customer_status ON complaints(customer_id,status,created_at DESC); CREATE INDEX idx_complaint_comments_parent ON complaint_comments(complaint_id,created_at); CREATE INDEX idx_ratings_customer ON service_ratings(customer_id,created_at DESC); CREATE INDEX idx_report_reviews_report ON report_reviews(report_id,review_status); CREATE INDEX idx_articles_status_category ON knowledge_base_articles(status,category,published_at DESC); CREATE INDEX idx_search_history_customer ON customer_search_history(customer_id,searched_at DESC);
CREATE TRIGGER trg_notification_templates_audit BEFORE UPDATE ON notification_templates FOR EACH ROW EXECUTE FUNCTION set_audit_columns(); CREATE TRIGGER trg_notifications_audit BEFORE UPDATE ON notifications FOR EACH ROW EXECUTE FUNCTION set_audit_columns(); CREATE TRIGGER trg_complaints_audit BEFORE UPDATE ON complaints FOR EACH ROW EXECUTE FUNCTION set_audit_columns(); CREATE TRIGGER trg_complaint_comments_audit BEFORE UPDATE ON complaint_comments FOR EACH ROW EXECUTE FUNCTION set_audit_columns(); CREATE TRIGGER trg_service_ratings_audit BEFORE UPDATE ON service_ratings FOR EACH ROW EXECUTE FUNCTION set_audit_columns(); CREATE TRIGGER trg_report_reviews_audit BEFORE UPDATE ON report_reviews FOR EACH ROW EXECUTE FUNCTION set_audit_columns(); CREATE TRIGGER trg_articles_audit BEFORE UPDATE ON knowledge_base_articles FOR EACH ROW EXECUTE FUNCTION set_audit_columns(); CREATE TRIGGER trg_favorites_audit BEFORE UPDATE ON customer_favorites FOR EACH ROW EXECUTE FUNCTION set_audit_columns(); CREATE TRIGGER trg_search_history_audit BEFORE UPDATE ON customer_search_history FOR EACH ROW EXECUTE FUNCTION set_audit_columns();
COMMENT ON TABLE notification_templates IS 'Localized multi-channel notification templates.'; COMMENT ON TABLE notifications IS 'Notification delivery and read-state ledger.'; COMMENT ON TABLE complaints IS 'Customer grievance cases.'; COMMENT ON TABLE complaint_comments IS 'Public and internal complaint discussion.'; COMMENT ON TABLE service_ratings IS 'Customer ratings for completed service requests.'; COMMENT ON TABLE report_reviews IS 'Controlled report review decisions.'; COMMENT ON TABLE knowledge_base_articles IS 'Publishable customer-support content.'; COMMENT ON TABLE customer_favorites IS 'Customer-saved properties and listings.'; COMMENT ON TABLE customer_search_history IS 'Customer search activity history.';
DO $$ DECLARE t text; c text; r record; BEGIN FOREACH t IN ARRAY ARRAY['notification_templates','notifications','complaints','complaint_comments','service_ratings','report_reviews','knowledge_base_articles','customer_favorites','customer_search_history'] LOOP FOREACH c IN ARRAY ARRAY['created_at','updated_at','created_by','updated_by','version'] LOOP EXECUTE format('COMMENT ON COLUMN %I.%I IS %L',t,c,'Standard audit metadata.'); END LOOP; END LOOP; FOR r IN SELECT table_name,column_name FROM information_schema.columns WHERE table_schema=current_schema() AND table_name=ANY(ARRAY['notification_templates','notifications','complaints','complaint_comments','service_ratings','report_reviews','knowledge_base_articles','customer_favorites','customer_search_history']) AND column_name NOT IN('created_at','updated_at','created_by','updated_by','version') LOOP EXECUTE format('COMMENT ON COLUMN %I.%I IS %L',r.table_name,r.column_name,replace(initcap(replace(r.column_name,'_',' ')),' Id',' identifier.')); END LOOP; END $$;
