CREATE TABLE monitoring_alerts (
 monitoring_alert_id UUID PRIMARY KEY DEFAULT gen_random_uuid(), monitoring_schedule_id UUID REFERENCES monitoring_schedules(monitoring_schedule_id) ON DELETE CASCADE, property_id UUID NOT NULL REFERENCES properties(property_id) ON DELETE CASCADE,
 service_request_id UUID REFERENCES service_requests(service_request_id) ON DELETE SET NULL, alert_type VARCHAR(50) NOT NULL, severity VARCHAR(20) NOT NULL, title VARCHAR(200) NOT NULL, description TEXT,
 detected_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP, acknowledged_by UUID REFERENCES users(user_id) ON DELETE SET NULL, acknowledged_at TIMESTAMPTZ, resolved_at TIMESTAMPTZ, status VARCHAR(20) NOT NULL DEFAULT 'OPEN',
 created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP, created_by UUID REFERENCES users(user_id) ON DELETE SET NULL, updated_by UUID REFERENCES users(user_id) ON DELETE SET NULL, version BIGINT NOT NULL DEFAULT 0,
 CONSTRAINT ck_alert_severity CHECK(severity IN('INFO','LOW','MEDIUM','HIGH','CRITICAL')), CONSTRAINT ck_alert_status CHECK(status IN('OPEN','ACKNOWLEDGED','RESOLVED','DISMISSED')), CONSTRAINT ck_alert_times CHECK((acknowledged_at IS NULL OR acknowledged_at>=detected_at) AND (resolved_at IS NULL OR resolved_at>=detected_at)), CONSTRAINT ck_alert_audit CHECK(updated_at>=created_at AND version>=0)
);
CREATE TABLE nri_relationship_assignments (
 nri_relationship_assignment_id UUID PRIMARY KEY DEFAULT gen_random_uuid(), customer_id UUID NOT NULL REFERENCES customers(customer_id) ON DELETE CASCADE, relationship_manager_user_id UUID NOT NULL REFERENCES users(user_id) ON DELETE RESTRICT,
 assigned_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP, unassigned_at TIMESTAMPTZ, status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE', assignment_reason TEXT,
 created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP, created_by UUID REFERENCES users(user_id) ON DELETE SET NULL, updated_by UUID REFERENCES users(user_id) ON DELETE SET NULL, version BIGINT NOT NULL DEFAULT 0,
 CONSTRAINT uq_nri_assignment_start UNIQUE(customer_id,assigned_at), CONSTRAINT ck_nri_assignment_status CHECK(status IN('ACTIVE','INACTIVE')), CONSTRAINT ck_nri_assignment_period CHECK(unassigned_at IS NULL OR unassigned_at>=assigned_at), CONSTRAINT ck_nri_assignment_audit CHECK(updated_at>=created_at AND version>=0)
);
CREATE UNIQUE INDEX uq_active_nri_manager ON nri_relationship_assignments(customer_id) WHERE status='ACTIVE' AND unassigned_at IS NULL;
CREATE TABLE nri_relationship_messages (
 nri_relationship_message_id UUID PRIMARY KEY DEFAULT gen_random_uuid(), nri_relationship_assignment_id UUID NOT NULL REFERENCES nri_relationship_assignments(nri_relationship_assignment_id) ON DELETE CASCADE,
 sender_user_id UUID NOT NULL REFERENCES users(user_id) ON DELETE RESTRICT, message_body TEXT NOT NULL, channel VARCHAR(20) NOT NULL DEFAULT 'IN_APP', sent_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP, read_at TIMESTAMPTZ,
 created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP, created_by UUID REFERENCES users(user_id) ON DELETE SET NULL, updated_by UUID REFERENCES users(user_id) ON DELETE SET NULL, version BIGINT NOT NULL DEFAULT 0,
 CONSTRAINT ck_nri_message_body CHECK(length(btrim(message_body))>0), CONSTRAINT ck_nri_message_channel CHECK(channel IN('IN_APP','EMAIL','SMS','WHATSAPP','PHONE_NOTE')), CONSTRAINT ck_nri_message_read CHECK(read_at IS NULL OR read_at>=sent_at), CONSTRAINT ck_nri_message_audit CHECK(updated_at>=created_at AND version>=0)
);
CREATE TABLE offline_sync_operations (
 offline_sync_operation_id UUID PRIMARY KEY DEFAULT gen_random_uuid(), user_id UUID NOT NULL REFERENCES users(user_id) ON DELETE CASCADE, device_id VARCHAR(255) NOT NULL,
 client_operation_id VARCHAR(160) NOT NULL, entity_type VARCHAR(80) NOT NULL, entity_id UUID, operation_type VARCHAR(20) NOT NULL, payload JSONB NOT NULL,
 client_occurred_at TIMESTAMPTZ NOT NULL, received_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP, processed_at TIMESTAMPTZ, status VARCHAR(20) NOT NULL DEFAULT 'RECEIVED', conflict_details JSONB, error_message TEXT,
 created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP, created_by UUID REFERENCES users(user_id) ON DELETE SET NULL, updated_by UUID REFERENCES users(user_id) ON DELETE SET NULL, version BIGINT NOT NULL DEFAULT 0,
 CONSTRAINT uq_offline_device_operation UNIQUE(device_id,client_operation_id), CONSTRAINT ck_offline_operation_type CHECK(operation_type IN('CREATE','UPDATE','DELETE')), CONSTRAINT ck_offline_payload CHECK(jsonb_typeof(payload)='object'), CONSTRAINT ck_offline_conflict CHECK(conflict_details IS NULL OR jsonb_typeof(conflict_details)='object'), CONSTRAINT ck_offline_status CHECK(status IN('RECEIVED','PROCESSING','APPLIED','CONFLICT','FAILED','IGNORED')), CONSTRAINT ck_offline_times CHECK(received_at>=client_occurred_at AND (processed_at IS NULL OR processed_at>=received_at)), CONSTRAINT ck_offline_audit CHECK(updated_at>=created_at AND version>=0)
);
CREATE TABLE refunds (
 refund_id UUID PRIMARY KEY DEFAULT gen_random_uuid(), payment_id UUID NOT NULL REFERENCES payments(payment_id) ON DELETE RESTRICT, refund_reference VARCHAR(120) NOT NULL UNIQUE,
 amount NUMERIC(15,2) NOT NULL, currency_code CHAR(3) NOT NULL DEFAULT 'INR', reason_code VARCHAR(50) NOT NULL, reason_details TEXT, status VARCHAR(20) NOT NULL DEFAULT 'REQUESTED',
 provider_refund_id VARCHAR(255), requested_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP, processed_at TIMESTAMPTZ, failed_at TIMESTAMPTZ,
 created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP, created_by UUID REFERENCES users(user_id) ON DELETE SET NULL, updated_by UUID REFERENCES users(user_id) ON DELETE SET NULL, version BIGINT NOT NULL DEFAULT 0,
 CONSTRAINT ck_refund_amount CHECK(amount>0), CONSTRAINT ck_refund_currency CHECK(currency_code~'^[A-Z]{3}$'), CONSTRAINT ck_refund_status CHECK(status IN('REQUESTED','APPROVED','PROCESSING','COMPLETED','FAILED','CANCELLED')), CONSTRAINT ck_refund_times CHECK((processed_at IS NULL OR processed_at>=requested_at) AND (failed_at IS NULL OR failed_at>=requested_at)), CONSTRAINT ck_refund_audit CHECK(updated_at>=created_at AND version>=0)
);
CREATE INDEX idx_monitoring_alerts_property ON monitoring_alerts(property_id,status,severity,detected_at DESC); CREATE INDEX idx_nri_assignments_manager ON nri_relationship_assignments(relationship_manager_user_id,status); CREATE INDEX idx_nri_messages_assignment ON nri_relationship_messages(nri_relationship_assignment_id,sent_at); CREATE INDEX idx_offline_sync_queue ON offline_sync_operations(status,received_at); CREATE INDEX idx_offline_sync_user ON offline_sync_operations(user_id,device_id,client_occurred_at); CREATE INDEX idx_refunds_payment ON refunds(payment_id,status,requested_at DESC);
CREATE TRIGGER trg_monitoring_alerts_audit BEFORE UPDATE ON monitoring_alerts FOR EACH ROW EXECUTE FUNCTION set_audit_columns(); CREATE TRIGGER trg_nri_assignments_audit BEFORE UPDATE ON nri_relationship_assignments FOR EACH ROW EXECUTE FUNCTION set_audit_columns(); CREATE TRIGGER trg_nri_messages_audit BEFORE UPDATE ON nri_relationship_messages FOR EACH ROW EXECUTE FUNCTION set_audit_columns(); CREATE TRIGGER trg_offline_sync_audit BEFORE UPDATE ON offline_sync_operations FOR EACH ROW EXECUTE FUNCTION set_audit_columns(); CREATE TRIGGER trg_refunds_audit BEFORE UPDATE ON refunds FOR EACH ROW EXECUTE FUNCTION set_audit_columns();
COMMENT ON TABLE monitoring_alerts IS 'Actionable alerts generated by property monitoring.'; COMMENT ON TABLE nri_relationship_assignments IS 'Effective-dated NRI customer relationship-manager allocation.'; COMMENT ON TABLE nri_relationship_messages IS 'Auditable NRI relationship communications.'; COMMENT ON TABLE offline_sync_operations IS 'Idempotent mobile offline-operation ingestion ledger.'; COMMENT ON TABLE refunds IS 'Payment refund lifecycle and provider reconciliation.';
DO $$ DECLARE t text; c text; r record; BEGIN FOREACH t IN ARRAY ARRAY['monitoring_alerts','nri_relationship_assignments','nri_relationship_messages','offline_sync_operations','refunds'] LOOP FOREACH c IN ARRAY ARRAY['created_at','updated_at','created_by','updated_by','version'] LOOP EXECUTE format('COMMENT ON COLUMN %I.%I IS %L',t,c,'Standard audit metadata.'); END LOOP; END LOOP; FOR r IN SELECT table_name,column_name FROM information_schema.columns WHERE table_schema=current_schema() AND table_name=ANY(ARRAY['monitoring_alerts','nri_relationship_assignments','nri_relationship_messages','offline_sync_operations','refunds']) AND column_name NOT IN('created_at','updated_at','created_by','updated_by','version') LOOP EXECUTE format('COMMENT ON COLUMN %I.%I IS %L',r.table_name,r.column_name,replace(initcap(replace(r.column_name,'_',' ')),' Id',' identifier.')); END LOOP; END $$;
